tags:
  - name: auth
    description: user authentication
  - name: transaction
    description: transactions

paths:
  # [POST] Auth
  /auth/signup:
    post:
      tags:
        - auth
      summary: User Signup
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/createUser"
          required: true
      responses:
        201:
          description: "successfully creates user"
        400:
          description: "Bad Request"
        500:
          description: "Internal Server Error"

  /auth/login:
    post:
      tags:
        - auth
      summary: User Login
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/loginUser"
          required: true
      responses:
        200:
          description: "returns authentication token"
        400:
          description: "Bad Request"
        409:
          description: "Incorrect user inputs"
        500:
          description: "Internal Server Error"

  /transaction/fund-own-account:
    post:
      tags:
        - transaction
      summary: user funds their account
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: Authorization
          in: header
          description: Authorization token
          required: true
          type: string
        - name: body
          in: body
          schema:
            type: object
            required:
              - amount
            properties:
              amount:
                type: integer
      responses:
        200:
          description: "successfully funds own account"
        400:
          description: "Bad request"
        401:
          description: "User authentication fails"
        500:
          description: "Internal Server Error"

/transaction/transfer-fund:
  post:
    tags:
      - transaction
    summary: transfer fund to another user
    consumes:
      - application/json
    produces:
      - application/json
    parameters:
      - name: Authorization
        in: header
        description: Authorization token
        required: true
        type: string
      - name: body
        in: body
        schema:
          type: object
          required:
            - amount
            - receiverId
          properties:
            amount:
              type: integer
            receiverId:
              type: integer
    responses:
      200:
        description: "Successfully transfer fund to the selected user"
      400:
        description: "Bad request"
      401:
        description: "User authentication fails"
      500:
        description: "Internal Server Error"

/transaction/withdraw-fund:
  post:
    tags:
      - transaction
    summary: user withdraw funds from account
    consumes:
      - application/json
    produces:
      - application/json
    parameters:
      - name: Authorization
        in: header
        description: Authorization token
        required: true
        type: string
      - name: body
        in: body
        schema:
          type: object
          required:
            - amount
          properties:
            amount:
              type: integer
    responses:
      200:
        description: "successfully withdraw funds"
      400:
        description: "Bad request"
      401:
        description: "User authentication fails"
      500:
        description: "Internal Server Error"

/transaction/user-transactions:
  get:
    tags:
      - transaction
    summary: All transactions
    consumes:
      - application/json
    produces:
      - application/json
    parameters:
      - name: Authorization
        in: header
        description: Authorization token
        required: true
        type: string
    responses:
      200:
        description: "Show all transactions"
      400:
        description: "Bad request"
      401:
        description: "User authentication fails"
      500:
        description: "Internal Server Error"

/transaction/user-balance:
  get:
    tags:
      - transaction
    summary: Fetches User Balance
    consumes:
      - application/json
    produces:
      - application/json
    parameters:
      - name: Authorization
        in: header
        description: Authorization token
        required: true
        type: string
    responses:
      200:
        description: "Show user balance"
      400:
        description: "Bad request"
      401:
        description: "User authentication fails"
      500:
        description: "Internal Server Error"

# --------------------------definitions--------------------------
definitions:
  createUser:
    type: object
    required:
      - firstName
      - lastName
      - email
      - password
    properties:
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
        format: email
      password:
        type: string
        format: password

  loginUser:
    type: object
    required:
      - email
      - password
    properties:
      email:
        type: string
        format: email
      password:
        type: string
        format: password
